name: Build and publish

on:
  release:
    types: [published, released]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Checkout last passing commit
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests
        run: pytest

      - name: Build stable distribution then publish to PyPI
        run: |
          rm -rf dist/*
          python -m pip install --upgrade build
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: $${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi



      
