name: Build and publish

on:
  release:
    types: [publish]

jobs:
  build_and_publish:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Checkout last passing commit
        uses: actions/checkout@v2
      
      - name: Build stable distribution
        run: |
          rm -rf dist/*
          python -m pip install --upgrade build
          python -m build

      # - name: Publish package to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}




      
