name: Build and publish

on:
  release:
    types: [published]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Checkout last passing commit
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"
          pip install git+https://github.com/NREL/ml4pd_models.git@v1

      - name: Run tests
        run: pytest

      - name: Build stable distribution
        run: |
          rm -rf dist/*
          python -m pip install --upgrade build
          python -m pip install twine
          python -m build
      
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TWINE_TOKEN }}


      
